### ISSUE TITLE
Add i18n support with crowdin

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1343]
### Summary

Add i18n support with crowdin

**Comment by bigint** [comment]
https://lingui.js.org/tools/crowdin.html

**Comment by andrii-bodnar** [comment]
Hi, would be happy to help with the Crowdin integration 🙂 
Please feel free to ask any questions regarding that

**Comment by foolo** [comment]
@bigint I worked a bit on this and have implemented a working solution (ported the website to LinguiJS and tested Crowdin integration).
One open question is where to put the language setting in the UI (e.g. in the profile menu, or under settings, etc). Do you have any opinion on that? (Right now I have put it under Settings > Account, but I don't know if that's the best place)
I can share a PR for comments.
@andrii-bodnar There's probably still help needed on the Crowdin website with organizing the project.

**Comment by andrii-bodnar** [comment]
Hi @foolo, sure, feel free to ask any questions you may have about organizing a Crowdin project

**Comment by bigint** [comment]
@foolo feel free to create a PR for it we can move discussion there 🙇🏼

**Comment by bigint** [comment]
We can put it in settings for now as an MVP, we can move it based on user request later 🚀 

I hope you add strings in packages folder and not inside apps/web, cuz these strings should be accessible across the apps

**Comment by foolo** [comment]
@bigint Ahh, no, currently they are in apps/web :) I'll move them packages folder, and create a PR after.

**Comment by foolo** [comment]
@bigint Or actually I'll create the PR first, because I'm not really sure I understand how to put the strings under /packages, (for example whether to create a new workspace, etc), I'm probably not enough experienced with yarn and npm :)
By the way, I you were talking about using the same strings for multiple apps, it may seem like a good idea, but it can also lead to a big mess because there will most likely be some language in which the translation is dependent on something that differs between the various usages of the same string. So I would say that the best practice is to have unique strings for every app, every page, etc, and let the CAT tool (Crowdin) take care of identifying identical or similar strings, and let the translator decide whether to translate them the same way or not. (I work with UI translation for a big tech company, so I have a bit of experience on all the caveats :) )
