### ISSUE TITLE
[Bug] [Visual] ENS Badge looking weird

### ISSUE THREAD

**Issue by donosonaumczuk** [lensterxyz/lenster#146]
### Summary

Evidence

![image](https://user-images.githubusercontent.com/23125060/181358755-b537cf5d-9337-4d64-a80b-5bb5fc18699c.png)

### What platform(s) does this occur on?

Web

**Comment by bigint** [comment]
@donosonaumczuk I can't able to reproduce this 😕 

![image](https://user-images.githubusercontent.com/69431456/181432552-bd06f447-31b8-4b97-bc32-13b9e5c19b80.png)

**Comment by donosonaumczuk** [comment]
Hmm weird. I'm using Firefox :thinking:

**Comment by donosonaumczuk** [comment]
I think might be an error related to the browser, is really weird. It actually loads well, but when I scroll that white bar appears

**Comment by AdamSchinzel** [comment]
Same for me

**Comment by foolo** [comment]
I tested with a modified PNG file so that the bug shows more clearly:
![Screenshot_2022-11-14_12-52-19](https://user-images.githubusercontent.com/667227/201653469-08fddd4a-e31e-4404-a2de-926cb234bcd9.png)

The artifact shows and hides as you move the mouse cursor over the page:
https://user-images.githubusercontent.com/667227/201653717-a6bb792c-4216-41fd-a4c9-e6be56049c4f.mp4

So it seems like this is a rendering bug in Firefox, which cannot be solved in Lenster (other than by randomly trying to change the design, and hope that the bug disappears).

@bigint Perhaps we can close this issue as not related to Lenster?

**Comment by bigint** [comment]
Thanks @foolo for digging in 🙏🏼
