### ISSUE TITLE
Unable to view all followers

### ISSUE THREAD

**Issue by xbwl20** [lensterxyz/lenster#2462]
![image](https://user-images.githubusercontent.com/74717674/230759801-ce3ec5fa-2d4b-4d3d-8954-6f687d6a4a66.png)

After clicking on 'follower', only one page of followers can be displayed, and the rest cannot be updated

**Comment by foolo** [comment]
This modal doesn't seem to have any pagination, i.e. it will always show **all** the followers. Instead, the problem may be that profile details show a too big Follower count, i.e. same as this issue: https://github.com/lensterxyz/lenster/issues/2536 so that the user expects to see more followers than there are.

**Comment by foolo** [comment]
Seems like the empty span is not detected by react-cool-inview:
`<span ref={observe} />`
in https://github.com/lensterxyz/lenster/blob/main/apps/web/src/components/Profile/Followers.tsx#L92

But it works if an empty space is added in the span tag, like this: `<span ref={observe}>&nbsp;</span>`
@bigint Do you think this is a reasonable workaround?

**Comment by foolo** [comment]
Solved by https://github.com/lensterxyz/lenster/pull/2737
