### ISSUE TITLE
Show warning message if user trying to save with checkmark or other prohibited emojis/symbols

### ISSUE THREAD

**Issue by saagu335** [lensterxyz/lenster#2575]
![Image](https://user-images.githubusercontent.com/69431456/232332792-7bee8508-c42e-4bdc-9110-aef78c66b9e6.png)

**Comment by foolo** [comment]
@saagu335 I guess this is about when saving the profile name in settings, right? (as in the screenshot below)
So if user clicks Save, there would be an error message, something like "Username must not contain forbidden symbols" ?

![Screenshot_2023-05-13_21-14-52](https://github.com/lensterxyz/lenster/assets/667227/76c398ba-95fa-4934-b8e8-465972fa6904)

**Comment by bigint** [comment]
Yup exactly @foolo also we should sanitize those symbols while rendering

**Comment by foolo** [comment]
> Yup exactly @foolo also we should sanitize those symbols while rendering

OK so for those users who have already managed to select a name with for example "✅", that symbol should be hidden when rendering their username anywhere on the website?

**Comment by foolo** [comment]
> Yup exactly @foolo also we should sanitize those symbols while rendering

@bigint OK, so for those users who have already managed to select a name with for example "white_check_mark", that symbol should be hidden when rendering their username anywhere on the website?

**Comment by bigint** [comment]
Both

**Comment by foolo** [comment]
> Both

@bigint Right, thanks!
I came to think of one tricky case though: How to handle searching by profile name, for users who already have a restricted character in their name. For example, if person A has the username "foo✅bar", other users will just see "foobar". But if a user types "foobar" in the search box, they won't find person A, because `SearchProfilesQuery` will match against the actual profile name: "foo✅bar".

Maybe this can be handled by showing a warning message to the "foo✅bar" user:

_"Your name contains restricted symbols, and you may not appear in search results. We recommend that you change your profile name."_
