### ISSUE TITLE
[Feature request] Post pinning

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#31]

**Comment by andriishupta** [comment]
Hello @bigint 👋 

I would like to help on this PR if it is open for "help wanted"

Please, describe high-level implementation if you already know you would do it:
- UI/UX: I guess it should be similar to Twitter functionality
- BE: I guess it should be similar as with existing Likes functionality about where to store and retrieve
- Chain: -

**Comment by bigint** [comment]
@andriishupta We still dependent on the Lens backend for this

cc @joshstevens19

**Comment by andriishupta** [comment]
@bigint, thanks for the quick answer!

so I could wait for API or start implementing FE's blueprint and then integrate API

this issue is the only one with "help wanted", but I could look for other issues - contribution.md says they are all "open for contribution" :)

also, if you already know what could be easily picked up right now and you want to delegate it - feel free to tag me there

**Comment by bigint** [comment]
@andriishupta I would suggest till API supports it 🙏🏼 

Also I'm adding more `help wanted` issues 🙇🏼

**Comment by bigint** [comment]
Will open it again when API supports it
