### ISSUE TITLE
Add more action in profile page

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#312]
- [x] Copy profile link
- [ ] Think more...

![Image](https://user-images.githubusercontent.com/69431456/183300615-d8ae0ed3-fa09-4733-81b2-7e62fd849538.png)

**Comment by AdamSchinzel** [comment]
My ideas:

1. Copy profile link
2. Send tip (related with #65)
3. View owner on PolygonScan

**Comment by bigint** [comment]
That's great idea 🚀 @AdamSchinzel

**Comment by AdamSchinzel** [comment]
Should I add it (for now without the send tip option)?

I think it would be nice to have these three dots that open up the options to the right from the edit profile button.

**Comment by AdamSchinzel** [comment]
Also when testing the search bar, I will add attribute auto-complete="off" because it look horrible when you search it with enter in the past.

<img width="486" alt="Screen Shot 2022-10-02 at 9 26 42 AM" src="https://user-images.githubusercontent.com/66002635/193443020-6d636e4a-e323-4636-86d1-d94ffce3543e.png">
