### ISSUE TITLE
Add search icon in mobile navbar

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#68]

**Comment by danschewy** [comment]
Where would you like the search icon?

**Comment by bigint** [comment]
![Screenshot 2022-07-25 at 1 27 55 PM](https://user-images.githubusercontent.com/69431456/180727379-14cfafb5-4780-4071-87d3-c8140b509e55.png)

![Screenshot 2022-07-25 at 1 28 11 PM](https://user-images.githubusercontent.com/69431456/180727440-cbc6096b-7745-417d-a28c-09368f29a320.png)

@danschewy in the search box in navbar something like twitter does 🙇🏻

**Comment by shanpriyan** [comment]
@bigint can we show search bar inside the header in mobile view? so that we can also show suggestions dropdown list.
![image](https://user-images.githubusercontent.com/42532987/181517586-3182a9ed-ef4e-4a4d-abf6-db7fd995bc5c.png)
![image](https://user-images.githubusercontent.com/42532987/181517751-5b166d08-abdb-45ea-bc1e-a315a27fd48c.png)

**Comment by bigint** [comment]
@shanpriyan it looks a bit messy, I think GitHub mobile has a good search bar that lives inside the expanded menu 🙇🏻
